# Generated by Django 5.2.5 on 2025-10-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_category',
            field=models.CharField(choices=[('NONE', 'None'), ('FEATURED', 'Featured'), ('POPULAR', 'Popular'), ('ARRIVED', 'Just Arrived')], default='NONE', max_length=10),
        ),
    ]
